name: List Organization Teams

on:
  workflow_dispatch:

jobs:
  list-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Teams
        id: get-teams
        run: |
          ACCESS_TOKEN="${{ secrets.ACCESS_TOKEN }}"
          ORG_NAME="clydetealium"

          teams=$(curl -s -H "Authorization: token $ACCESS_TOKEN" \
                  "https://api.github.com/orgs/$ORG_NAME/teams")

          echo "$teams" >> teams.json
          echo "TEAMS_JSON=$(cat teams.json)" >> $GITHUB_ENV
      
      - name: Get Repositories
        id: get-repos
        run: |
          ACCESS_TOKEN="${{ secrets.ACCESS_TOKEN }}"
          ORG_NAME="clydetealium"

          repos=$(curl -s -H "Authorization: token $ACCESS_TOKEN" \
                  "https://api.github.com/orgs/$ORG_NAME/repos")

          echo "$repos" >> repos.json
          echo "REPOS_JSON=$(cat repos.json)" >> $GITHUB_ENV
